### ISSUE TITLE
Update vendored assets to 5.0?

### ISSUE THREAD

**Issue by benjiwheeler** [fixlr/codemirror-rails#35]
Hi, I was trying to figure out why my rails codemirror editor was buggy where the demo editor on the codemirror site is not, when running coffeescript mode on ios safari. 

turns out if i just replace codemirror-rails's codemirror.js v4.8 with the current codemirror 5.0, it fixes the problem. 

could you please update the version of codemirror.js? if the only files that need to change are codemirror.js and .css, i'd be happy to create a pull request with those changes.

**Comment by fixlr** [comment]
Hi @benjiwheeler. I pushed several new builds of the gem today, covering all the missed codemirror versions. Enjoy!
