### ISSUE TITLE
CodeMirror.multiplexingMode is not a function

### ISSUE THREAD

**Issue by haslinger** [fixlr/codemirror-rails#37]
On an existing old rails application now running on codemirror-rails 5.3, that worked before,  in current Chrome and Firefox I suddenly get the Javascript error messages
```
Uncaught TypeError: CodeMirror.multiplexingMode is not a function
Uncaught TypeError: Cannot read property 'startState' of undefined
```
and the warning
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

I didn't enable anything special and I have currently no idea what's going on here.
Same application on the server with 5.2 has no issues.

No I went back in development to 5.2, but that didn't help.

Any suggestions or ideas welcome!

**Comment by haslinger** [comment]
Update:
I can resolve the issue when I disable
```
//= require codemirror/modes/htmlmixed
```
Still, I would be interested, what's going wrong here...

**Comment by fixlr** [comment]
@haslinger I think you must mean CodeMirror 5.3? I haven't pushed codemirror-rails 5.3 yet.

**Comment by haslinger** [comment]
Checked in my Gemfile lock again. It's 5.2. (I have no idea...). I will now investigate further ...
