### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by voxik** [fixlr/codemirror-rails#52]
Could you please push the tags for the latest releases? They are missing in the repository. Thank you.

**Comment by voxik** [comment]
Actually, now I am looking that it is not just tags ... I can't see any code relevant to 5.16.0

**Comment by fixlr** [comment]
@voxik Ah yes, you are correct. I pushed them to a branch to trigger a CI build, but not to master. Everything up to 5.16 should be available now. Thanks!
